---
- hosts: AnsibleHost
  gather_facts: no
  vars:
  tasks:
  - name: Stop Elasticsearch
    command: docker stop elasticsearch
  
  - name: Backup Elasticsearch
    command: "{{ item }}"
    with_items:
      - rclone copy /SINGLEPOOL/home/config/elasticsearch googledrive:files/config/elasticsearch
   
  - name: Start Elasticsearch
    command: docker start elasticsearch  
      
  - name: Backup all other config files
    command: "{{ item }}"
    with_items:
      - rclone copy /SINGLEPOOL/home/config/pihole googledrive:files/config/pihole
      - rclone copy /SINGLEPOOL/home/config/guacamole googledrive:files/config/guacamole
      - rclone copy /SINGLEPOOL/home/config/guacamole googledrive:files/config/guacd
      - rclone copy /SINGLEPOOL/home/config/heimdall googledrive:files/config/heimdall
      - rclone copy /SINGLEPOOL/home/config/sonarr googledrive:files/config/sonarr
      - rclone copy /SINGLEPOOL/home/config/portainer googledrive:files/config/portainer
      - rclone copy /SINGLEPOOL/home/config/grafana googledrive:files/config/grafana
      - rclone copy /SINGLEPOOL/home/config/traefik googledrive:files/config/traefik
      - rclone copy /SINGLEPOOL/home/config/telegraf googledrive:files/config/telegraf
      - rclone copy /SINGLEPOOL/home/config/tautulli googledrive:files/config/tautulli
      - rclone copy /SINGLEPOOL/home/config/radarr googledrive:files/config/radarr
      - rclone copy /SINGLEPOOL/home/config/ddclient googledrive:files/config/ddclient
      - rclone copy /SINGLEPOOL/home/config/filebeat googledrive:files/config/filebeat
      - rclone copy /SINGLEPOOL/home/config/piaopenvpn googledrive:files/config/piaopenvpn
      - rclone copy /SINGLEPOOL/home/config/python googledrive:files/config/python      
      - rclone copy /SINGLEPOOL/home/config/nzbget googledrive:files/config/nzbget
      - rclone copy /SINGLEPOOL/home/config/deluge googledrive:files/config/deluge           
      - rclone copy /SINGLEPOOL/home/config/rpi googledrive:files/config/rpi
      - rclone copy /SINGLEPOOL/home/config/scripts googledrive:files/config/scripts
