---
- hosts: AnsibleHost
  gather_facts: no
  vars:
  tasks:
  - name: Stop containers
    command: "{{ item }}"
    with_items:
#      - docker stop elasticsearch
      - docker stop influxdb
      - docker stop mysql
      - docker stop pihole
      - docker stop plex
      
  - name: Backup config files
    command: "{{ item }}"
    with_items:
#      - rclone copy /SSDPOOL/home/config/elasticsearch googledrive:files/config/elasticsearch
      - rclone copy /SSDPOOL/home/config/influxdb GOOGLEPOOL:files/config/influxdb
      - rclone copy /SSDPOOL/home/config/mysql GOOGLEPOOL:files/config/mysql
      - rclone copy /SSDPOOL/home/config/python GOOGLEPOOL:files/config/python
      - rclone copy /SSDPOOL/home/config/pihole GOOGLEPOOL:files/config/pihole
    ignore_errors: True      
      
  - name: Start containers
    command: "{{ item }}"
    with_items:
#      - docker start elasticsearch
      - docker start influxdb
      - docker start mysql
      - docker start pihole
      - docker start plex

  - name: Backup all other config files
    command: "{{ item }}"
    with_items:
      - rclone copy /SSDPOOL/home/config/pihole GOOGLEPOOL:files/config/pihole
      - rclone copy /SSDPOOL/home/config/guacamole GOOGLEPOOL:files/config/guacamole
      - rclone copy /SSDPOOL/home/config/guacamoleinternal GOOGLEPOOL:files/config/guacamoleinternal
      - rclone copy /SSDPOOL/home/config/guacd GOOGLEPOOL:files/config/guacd
      - rclone copy /SSDPOOL/home/config/guacdinternal GOOGLEPOOL:files/config/guacdinternal
      - rclone copy /SSDPOOL/home/config/heimdall GOOGLEPOOL:files/config/heimdall
      - rclone copy /SSDPOOL/home/config/heimdalldenmans GOOGLEPOOL:files/config/heimdalldenmans      
      - rclone copy /SSDPOOL/home/config/sonarr GOOGLEPOOL:files/config/sonarr
      - rclone copy /SSDPOOL/home/config/portainer2 GOOGLEPOOL:files/config/portainer2
      - rclone copy /SSDPOOL/home/config/grafana GOOGLEPOOL:files/config/grafana
      - rclone copy /SSDPOOL/home/config/traefik GOOGLEPOOL:files/config/traefik
      - rclone copy /SSDPOOL/home/config/telegraf GOOGLEPOOL:files/config/telegraf
      - rclone copy /SSDPOOL/home/config/tautulli GOOGLEPOOL:files/config/tautulli
      - rclone copy /SSDPOOL/home/config/radarr GOOGLEPOOL:files/config/radarr
      - rclone copy /SSDPOOL/home/config/ddclient GOOGLEPOOL:files/config/ddclient
      - rclone copy /SSDPOOL/home/config/filebeat GOOGLEPOOL:files/config/filebeat
      - rclone copy /SSDPOOL/home/config/piaopenvpn GOOGLEPOOL:files/config/piaopenvpn
      - rclone copy /SSDPOOL/home/config/nzbget GOOGLEPOOL:files/config/nzbget
      - rclone copy /SSDPOOL/home/config/deluge GOOGLEPOOL:files/config/deluge           
      - rclone copy /SSDPOOL/home/config/rpi GOOGLEPOOL:files/config/rpi
      - rclone copy /SSDPOOL/home/config/scripts GOOGLEPOOL:files/config/scripts
      - rclone copy /SSDPOOL/home/config/calibre-web GOOGLEPOOL:files/config/calibre-web
      - rclone copy /SSDPOOL/home/config/cloudflareddns GOOGLEPOOL:files/config/cloudflareddns
      - rclone copy /SSDPOOL/home/config/awx GOOGLEPOOL:files/config/awx
      - rclone copy /SSDPOOL/home/config/unifi GOOGLEPOOL:files/config/unifi
      - rclone copy /SSDPOOL/home/config/statping GOOGLEPOOL:files/config/statping
      - rclone copy /SSDPOOL/home/config/scrutiny GOOGLEPOOL:files/config/scrutiny
      - rclone copy /SSDPOOL/home/config/bookstack GOOGLEPOOL:files/config/bookstack
      - rclone copy /SSDPOOL/home/config/scrutiny GOOGLEPOOL:files/config/scrutiny      
      
      
