---
- hosts: AnsibleHost
  gather_facts: no
  connection: local
  vars:
  tasks:
  - name: Copy Files
    copy  :
      remote_src: yes
      src: /SINGLEPOOL/home/config
      dest: /GOOGLEPOOL/home/config
